version: '3.1'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        image: jenkins-master
    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        image: jenkins-slave_mvn1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /Users/vineshkumar/jenkins_slave_home:/home/jenkins
            - /Users/vineshkumar/jenkins_slave_mavenhome:/usr/share/maven
        depends_on:
            - jenkins
